# Generated by Django 5.2.3 on 2025-11-09 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('map_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_start', models.DateTimeField(db_index=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ticket_link', models.URLField(blank=True, null=True)),
                ('event_link', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concerts', to='concerts.venue')),
            ],
            options={
                'ordering': ['-date_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='concerts.concert')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('concert', 'order'), name='uniq_program_order_per_concert')],
            },
        ),
    ]
