# Generated by Django 5.1.2 on 2026-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='map_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
