# Generated by Django 5.1.2 on 2026-06-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_venue_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
